'use client';

import './globals.css';
import '../style/index.scss';
import AppProvider from '@/contextApi/AppProvider';
import ReduxProvider from '@/redux/ReduxProvider';
import initI18next from './i18next-init';
import { appWithTranslation, useTranslation } from 'next-i18next';
import { Toaster } from 'react-hot-toast';

initI18next();

const RootLayout = ({ children }: any) => {
  const { t } = useTranslation()
  return (
    <html lang="en">
      <head>
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="description" content="Generated by create next app" />
        <meta name="robots" content="noindex, follow" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />
        <title>{t("JasPharm - Onlayn tibbiy xizmatlar kompaniyasi")}</title>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body suppressHydrationWarning={true}>

        <div>
          <Toaster position='top-center' />
        </div>
        <ReduxProvider>
          <AppProvider>
            {children}
          </AppProvider>
          {/* <ToastContainer
            position="top-left"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
          /> */}
        </ReduxProvider>
      </body>
    </html>
  );
};

export default appWithTranslation(RootLayout);